apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
namespace: argocd

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - "server.insecure=true"
      # - "server.rootpath=argocd"

# configMapGenerator:
#   - name: argocd-cm
#     behavior: merge
#     literals:
#       - "timeout.reconciliation=15s"
#
# patches:
#   # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
#   - target:
#       group: rbac.authorization.k8s.io
#       version: v1
#       kind: ClusterRoleBinding
#     patch: |-
#       - op: replace
#         path: /subjects/0/namespace
#         value: default
